### ISSUE TITLE
Sunshine crashes when using "Command" rather than Detatched Command

### ISSUE THREAD

**Issue by joeknock90** [SunshineStream/Sunshine#260] opened 2022-07-21 18:13 UTC
### Describe the Bug

When using a command for the main application to run: I.E. 
`steam steam://rungameid/${insertgameidhere}`

The sunshine server crashes. 

The built in Big Picture works using a detached command, which if I am reading the difference properly, means that after quitting big picture, keeps the stream alive because moonlight does not detect that the process has ended. 

Please let me know if I am reading the documentation on these entries properly. 

### Expected Behavior

Sunshine should stream the game and quit the stream when the application is exited. 

### Sunshine Host Operating System and Version

Arch Linux 

### Architecture

x64

### Sunshine Version

0.14.0

### GPU Type

AMD

### GPU Model

6900XT

### GPU Driver/Mesa Version

Mesa 22.1.3

### Capture Method (Linux Only)

X11 with VA-API

**Comment by ReenigneArcher** [comment] 2022-07-21 18:19
Please put your actual command, with the game id.

**Comment by joeknock90** [comment] 2022-07-21 18:24
`steam steam://rungameid/1332010`

**Comment by ReenigneArcher** [comment] 2022-07-21 18:49
Detached means that Sunshine will run the command and forget about. I.e. it is not a subprocess of Sunshine.

Depending on the game/application you may need to run it detached instead of as a command. Sunshine has no control over how a game process is executed. Some processes end almost immediately and launch another process. In this case Sunshine would only know about the first process and because it ends very quickly, Sunshine will end the stream.

Detached commands will not end when you quit the stream; however.

Also going to close this as it's not a bug with Sunshine. If you need additional support reach us on our discord server.

**Closed** 2022-07-21 18:49 UTC
Labels: invalid:support
