### ISSUE TITLE
Unable to find encoder

### ISSUE THREAD

**Issue by emmyoh** [SunshineStream/Sunshine#69] opened 2022-02-26 00:36 UTC
### Describe the Bug

Having switched from the original repository's version of Sunshine to this fork, Sunshine no longer runs at all, with the process aborting due to a fatal error mere moments after starting it.

Below is the output I get on every run:
```
[2022:02:25:19:21:44]: Error: Failed to gain CAP_SYS_ADMIN
[2022:02:25:19:21:44]: Error: Couldn't expose some/all drm planes for card: /dev/dri/card0
[2022:02:25:19:21:44]: Info: Detecting connected monitors

[2022:02:25:19:21:44]: Info: //////////////////////////////////////////////////////////////////
[2022:02:25:19:21:44]: Info: //                                                              //
[2022:02:25:19:21:44]: Info: //   Testing for available encoders, this may generate errors.  //
[2022:02:25:19:21:44]: Info: //   You can safely ignore those errors.                        //
[2022:02:25:19:21:44]: Info: //                                                              //
[2022:02:25:19:21:44]: Info: //////////////////////////////////////////////////////////////////
[2022:02:25:19:21:44]: Info: Trying encoder [nvenc]
[2022:02:25:19:21:44]: Info: Screencasting with X11
[2022:02:25:19:21:44]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:44]: Info: Color range: [JPEG]
[2022:02:25:19:21:44]: Error: Could not open codec [h264_nvenc]: Function not implemented
[2022:02:25:19:21:44]: Info: Screencasting with X11
[2022:02:25:19:21:44]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:44]: Info: Color range: [JPEG]
[swscaler @ 0x5635aa687e80] bad src image pointers
[2022:02:25:19:21:44]: Error: Couldn't convert image to required format and/or size
[2022:02:25:19:21:44]: Info: Screencasting with X11
[2022:02:25:19:21:44]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:44]: Info: Color range: [JPEG]
[2022:02:25:19:21:44]: Error: Could not open codec [h264_nvenc]: Function not implemented
[2022:02:25:19:21:44]: Info: Screencasting with X11
[2022:02:25:19:21:44]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:44]: Info: Color range: [JPEG]
[swscaler @ 0x5635aa223700] bad src image pointers
[2022:02:25:19:21:44]: Error: Couldn't convert image to required format and/or size
[2022:02:25:19:21:45]: Info: Encoder [nvenc] failed
[2022:02:25:19:21:45]: Info: Trying encoder [vaapi]
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[2022:02:25:19:21:45]: Info: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2022:02:25:19:21:45]: Error: Couldn't initialize va display: unknown libva error
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[2022:02:25:19:21:45]: Info: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2022:02:25:19:21:45]: Error: Couldn't initialize va display: unknown libva error
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[2022:02:25:19:21:45]: Info: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2022:02:25:19:21:45]: Error: Couldn't initialize va display: unknown libva error
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[2022:02:25:19:21:45]: Info: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2022:02:25:19:21:45]: Error: Couldn't initialize va display: unknown libva error
[2022:02:25:19:21:45]: Info: Encoder [vaapi] failed
[2022:02:25:19:21:45]: Info: Trying encoder [software]
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[swscaler @ 0x5635ab1e9040] bad src image pointers
[2022:02:25:19:21:45]: Error: Couldn't convert image to required format and/or size
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[swscaler @ 0x5635abde9040] bad src image pointers
[2022:02:25:19:21:45]: Error: Couldn't convert image to required format and/or size
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[swscaler @ 0x5635aa17a340] bad src image pointers
[2022:02:25:19:21:45]: Error: Couldn't convert image to required format and/or size
[2022:02:25:19:21:45]: Info: Screencasting with X11
[2022:02:25:19:21:45]: Info: Color coding [Rec. 601]
[2022:02:25:19:21:45]: Info: Color range: [JPEG]
[swscaler @ 0x5635aa17a340] bad src image pointers
[2022:02:25:19:21:45]: Error: Couldn't convert image to required format and/or size
[2022:02:25:19:21:45]: Info: Encoder [software] failed
[2022:02:25:19:21:45]: Info: 
[2022:02:25:19:21:45]: Info: //////////////////////////////////////////////////////////////
[2022:02:25:19:21:45]: Info: //                                                          //
[2022:02:25:19:21:45]: Info: // Ignore any errors mentioned above, they are not relevant //
[2022:02:25:19:21:45]: Info: //                                                          //
[2022:02:25:19:21:45]: Info: //////////////////////////////////////////////////////////////
[2022:02:25:19:21:45]: Info: 
[2022:02:25:19:21:45]: Fatal: Couldn't find any encoder
```

### Expected Behavior

Sunshine should run and work properly as it did before this forked version was created.

### Additional Context

Two other users on the Arch User Repository (AUR) have encountered this very same issue—[@JPenuchot](https://aur.archlinux.org/account/JPenuchot) and [@pogojotz](https://aur.archlinux.org/account/pogojotz).
Like me, [@JPenuchot](https://aur.archlinux.org/account/JPenuchot) had switched from the pre-fork version to the version hosted on this GitHub repository. However, [@pogojotz](https://aur.archlinux.org/account/pogojotz) had not installed the unmaintained version of Sunshine; this eliminates the possibility that some leftover files from before I made the switch are causing problems.
The other two mentioned are also running Arch Linux with Nvidia GPUs on X11.

### Sunshine Host Operating System and Version

Arch Linux

### Architecture

x86-64

### Sunshine Version

git

### GPU Type

Nvidia

### GPU Model

GeForce GTX 970

### GPU Driver/Mesa Version

510.54

### Capture Method (Linux Only)

X11 GNOME Session

**Comment by emmyoh** [comment] 2022-02-26 01:04
Perhaps this is related to the FFmpeg 5.0 release?
How may I help with debugging this?

**Comment by cyl3x** [comment] 2022-02-26 17:26
same issue here, Arch and NVIDIA Card

**Comment by JPenuchot** [comment] 2022-02-26 19:01
Update: The CMake script actually finds the CUDA install present on my system, although not when being called through makepkg when building the AUR package. Not sure the lack of a CUDA compiler is what's causing the error, but maybe what's causing CMake to not find nvcc could also be causing it to not find an essential library.

**Comment by JPenuchot** [comment] 2022-02-26 19:44
After a bit of debugging it turns out the issue happens here:
https://github.com/SunshineStream/Sunshine/blob/4a483078ad983b159d349e8056fccf61d918dc74/sunshine/video.cpp#L740

Both this fork and the original repo are impacted.

**Comment by JPenuchot** [comment] 2022-02-26 19:52
Another note: I don't get this issue on my laptop with Intel integrated graphics. It's possible that it was caused by a libdrm or Nvidia update too.

**Comment by ReenigneArcher** [comment] 2022-02-26 21:38
The AUR was recently updated and there were changes in the build besides pointing to this repo. There were 3 commits a few days ago https://aur.archlinux.org/cgit/aur.git/log/?h=sunshine

**Comment by JPenuchot** [comment] 2022-02-26 21:46
> OK … so it's not a regression introduced from the fork (so is not due to a code change), is not unique to Nvidia, but may possibly still be connected to something with Arch Linux? I'm quite lost as to what the cause could be. I had the pre-fork version of Sunshine installed an hour before opening this issue, and my system was 100% up-to-date at the time, so the only updates that could've possibly affected things is anything statically-linked to the compiled binary.

The issue points to avcodec, and it is statically linked indeed. I'll have a look at their bug tracker to find out if there's been any sort of regression.

> The fact that it works on Intel is interesting.

Not 100% sure but as far as I know my 6300U doesn't have any hardware encoder

**Comment by JPenuchot** [comment] 2022-02-26 22:14
Sorry I just found out I forgot to build Sunshine with ffmpeg 4.4, so I just polluted this issue with something that's already been solved here: https://github.com/SunshineStream/Sunshine/issues/63

I've added the CMake flags to link against ffmpeg 4.4 and I'm back to the `Couldn't expose some/all drm planes for card: /dev/dri/card0` error

**Comment by cyl3x** [comment] 2022-02-27 09:17
I fixed my issue by adding `-DLIBSWSCALE_INCLUDE_DIR=/usr/include/ffmpeg4.4 -DLIBSWSCALE_LIBRARIES=/usr/lib/ffmpeg4.4/libswscale.so` as CMAKE Flags in the PKGBUILD from AUR

**Comment by pogojotz** [comment] 2022-02-27 12:13
I can confirm that @cyl3x's solution works. Cheers for that 🍻

**Comment by JPenuchot** [comment] 2022-02-27 12:38
Back to business indeed. Thanks a lot :)

**Comment by pogojotz** [comment] 2022-03-01 09:33
This has been resolved in the AUR. Can be closed.

**Closed** 2022-03-01 16:16 UTC
Labels: os:Linux:Arch

**Comment by VRKade11** [comment] 2024-03-03 03:19
do you mind if you elaborate on the solution a little bit I have the code but I don't know where to put it

**Comment by ReenigneArcher** [comment] 2024-03-03 03:21
@VRKade11 you need to set the `DISPLAY` environment variable

**Comment by VRKade11** [comment] 2024-03-03 03:23
Well I figured it out it was the output name and adapter name needed to be blank or I messed something up with the name
