### ISSUE TITLE
Rumble causes game Freeze

### ISSUE THREAD

**Issue by jkms** [SunshineStream/Sunshine#65] opened 2022-02-24 18:59 UTC
### Describe the Bug

When streaming a game to my `moonlight` client, rumble causes the game to freeze for ~60 seconds, then recover.

### Expected Behavior

Rumble should either work, or perhaps not work?  But it definitely **shouldn't** cause the game to come to a complete hault for 60 seconds

### Additional Context

This bug is also documented in the [loki-47-6F-64 repo here](https://github.com/loki-47-6F-64/sunshine/issues/255)
Client: `moonlight`
Client Platform: `raspberry pi`
Client Controller: `Sony DualShock 4`

### Sunshine Host Operating System and Version

Fedora 35

### Architecture

64 bit

### Sunshine Version

0.12.0

### GPU Type

nVidia

### GPU Model

2060 Max Q

### GPU Driver/Mesa Version

510.47.03

### Capture Method (Linux Only)

X11

**Comment by HomerSp** [comment] 2022-03-08 20:13
Same here. It's caused by https://github.com/loki-47-6F-64/sunshine/commit/1f7bdb1b2a19444b5f9394f237a191cb6cd4dc6f. Basically, the pollfds are copied to a temporary vector (polls_tmp), which is then used to call poll, but the returned events are never copied to the proper vector (polls), it hangs looking for incoming events. A simple fix would be to just copy back the returned events from polls_tmp to polls.

**Comment by KuleRucket** [comment] 2022-03-09 17:18
I think I have this problem with Dirt 5 and Grid 2019/ I'll test again after the PR is merged.

**Comment by ReenigneArcher** [comment] 2022-03-09 18:01
> I think I have this problem with Dirt 5 and Grid 2019 I'll test again after the PR is merged.

If you'd like you can test the PR build. https://github.com/SunshineStream/Sunshine/actions/runs/1958438569

**Comment by KuleRucket** [comment] 2022-03-09 19:54
I can't use the builds as I'm on Arch. But I pasted the fix into my own build and it worked great. No freezing and the first rumble comes exactly when the game used to freeze.

**Comment by KuleRucket** [comment] 2022-03-09 19:57
Seems odd make a copy and then copy everything into a tmp vector and then back again but I'm sure loki had his reasons.

**Comment by HomerSp** [comment] 2022-03-10 07:58
Thanks for testing! I've updated the PR to have it make a bit more sense - it will no longer copy back the revents to the polls vector since it's not checked anywhere outside of the rumbleIterate function.
Using a temporary vector is still required, however, since polls is a vector of pollfd_t, and that's a container class for pollfd. I think loki realised that taking the address of the pollfd member of the first polls object was a bad idea since there may be padding in-between the polls objects, which would mean that the pollfd members won't be stored in contiguous memory.

**Comment by KuleRucket** [comment] 2022-03-10 10:56
Looks good. Especially the --x for avoiding missed events. I wonder what the effect of this bug was. Maybe missing rumbles?

Anyway, I'll try it out tonight.

**Comment by KuleRucket** [comment] 2022-03-10 12:47
Just built the PR branch directly and it works fine for me.

**Comment by jkms** [comment] 2022-03-11 01:22
Also built the PR.  Works for me as well.

**Closed** 2022-06-15 22:29 UTC
Labels: fixed, os:Linux:Fedora
